### ISSUE TITLE
The view size after zooming in doesn't get remembered after the application restart

### ISSUE THREAD

**Issue by Saltomar** [stacks-task-manager/stacks#138]
Hello,

The view size after zooming in doesn't get remembered after the application restart. 
Plus, the resizing scale isn't a proportionate. Sometimes it resizes more, sometimes less.

1. Click on left-top menu
2. Click on 'View >> Zoom in' 
3. Restart the Stacks application

Using Stacks on Windows 10 Pro with the latest updates.

Cheers.

**Comment by synapse** [comment]
@Saltomar fixed in v1.9.9

**Comment by Saltomar** [comment]
> @Saltomar fixed in v1.9.9

Where exactly? Can't find it in the menus.

Cheers.

**Comment by synapse** [comment]
It just works out of the box without any menu

**Comment by Saltomar** [comment]
@synapse 

I've updatet to the latest 1.9.10 version, but it still doesn't work properly. Pease check the screen cast of the issue:

https://screencast-o-matic.com/watch/c3iwcKVZUb8

Thanks.

**Comment by Saltomar** [comment]
Actually, sometimes, if I minimize then restore the window with the window command icons, after restarting the application, then it works, but it still doesn't remember the exact resizing ratio.
